# Generated by Django 4.2.5 on 2023-09-14 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('usr_employer_lookup_id', models.UUIDField()),
                ('usr_agency_lookup_id', models.UUIDField()),
                ('usr_employeemanager_ukraine_id', models.UUIDField()),
                ('usr_employee_manager_europe_id', models.UUIDField()),
                ('usr_scroll_lookup_id', models.UUIDField()),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
    ]
