# Generated by Django 4.2.5 on 2023-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('usrpartnertypeid', models.UUIDField(blank=True, null=True)),
                ('usragencythatgiveusemployerid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=20, null=True)),
                ('usremployerlookupid', models.UUIDField(blank=True, null=True)),
                ('usragencylookupid', models.UUIDField(blank=True, null=True)),
                ('usremployeemanagerukraineid', models.UUIDField(blank=True, null=True)),
                ('usremployeemanagereuropeid', models.UUIDField(blank=True, null=True)),
                ('usrscrolllookupid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('fulljobtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partnertype',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'partnertype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'profession',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
