# Generated by Django 4.2.5 on 2023-09-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='name_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.manager'),
            preserve_default=False,
        ),
    ]
