# Generated by Django 4.2.5 on 2023-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=20, null=True)),
                ('usremployerlookupid', models.UUIDField(blank=True, null=True)),
                ('usragencylookupid', models.UUIDField(blank=True, null=True)),
                ('usremployeemanagerukraineid', models.UUIDField(blank=True, null=True)),
                ('usremployeemanagereuropeid', models.UUIDField(blank=True, null=True)),
                ('usrscrolllookupid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
    ]
