# Generated by Django 4.2.5 on 2023-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tested',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uuid_id', models.UUIDField(blank=True, null=True)),
                ('name_cont', models.CharField(max_length=20)),
                ('phone_cont', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
    ]
