# Generated by Django 4.2.5 on 2023-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_tested_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tested',
            name='name_cont',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tested',
            name='phone_cont',
            field=models.CharField(max_length=255),
        ),
    ]
