# Generated by Django 4.2.5 on 2023-09-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_tested_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tested',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
