# Generated by Django 4.2.5 on 2023-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_tested_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tested',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
